- datacake.yml
- templates.yml
Adding Datacake webhook template
> Add Datacake webhook template

- templates.yml
- thingspeak.yml
Adding ThingSpeak webhook template.
> Introducing ThingSpeak webhook template

- qubitro.yml
- templates.yml
Adding Qubitro webhook template (#10)
> Add Qubitro webhook template

- templates.yml
Changing `templates.yml` to order webhook templates alphabetically.
Ref: #24
> Order templates alphabetically

- dezem.yml
- templates.yml
Create deZem webhook template
- new template in `dezem.yml`
- update index `templates.yml` and respect alphabetical order
The changes are proposed with effort to be aligned with the other templates. Let me know if anything should be done otherwise.
> Create deZem webhook template

- cayenne.yml
- templates.yml
Add Cayenne webhook template.
This template has been tested with a local TTNv3 stack.
> feat: mydevices cayenne integration

- iotinabox.yml
- templates.yml
Add IoTinaBox template
Tested with a local stack
> feat: mydevices iotinabox integration

- templates.yml
- uib.yml
New template for UIB Whatsapp Messaging
Notification will be sent to specified WhatsApp numbers if there is a warning 
- Added uib.yml file for UIB template 
- Modified template.yml to add uib
...
- [*] Scope: The referenced issue is addressed, there are no unrelated changes.
- [*] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [*] Testing: The changes are tested.
- [*] Documentation: Relevant documentation is added or updated.
> uib template 

- ubidots.yml
Update the template to use Ubidots' Plugins feature for the Webhook integration (instead of UbiFunctions).
- [Integration guide](https://help.ubidots.com/en/articles/5096476-plugins-connect-the-things-stack-to-ubidots)
The .yml file was created and tested by Ubidots team.
> Update Ubidots webhook template

- akenza.yml
- datacake.yml
- dezem.yml
- example.yml
- iotinabox.yml
- qubitro.yml
- tago.yml
- thethingsio.yml
- thingspeak.yml
- ubidots.yml
- uib.yml
This pull request fixes some (potentially) problematic YAML. 
- Fix quotes in Ubidots template
- Remove empty fields (alternatively, I can just put `""`, let me know if you think that's better)
> Fix (potentially) problematic YAML

- cloudstudio.yml
- templates.yml
Add Cloud Studio Webhook template
- Add Cloud Studio Webhook template
- [ X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ X] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [ X] Testing: The changes are tested.
- [ X] Documentation: Relevant documentation is added or updated.
> Add Cloud Studio webhook template

- homey.yml
New template for a 'Homey' home automation device 
New template
Homey manufacturers guidelines from:
https://apps.developer.homey.app/cloud/webhooks
- [*] Scope: The referenced issue is addressed, there are no unrelated changes.
- [*] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [*] Testing: The changes are tested.
- [*] Documentation: Relevant documentation is added or updated.
> Adding a new template for Homey

- homey.yml
Adding logo for Homey template
> Add Homey logo

- attmaker.yml
- templates.yml
Adds template for AllThingsTalk webhook.
- Template for AllThingsTalk webhook is added
Ran the ThingsStack locally but for some reason it didn't work with specified template directory so that's why I didn't check `Testing` part in the checklist.
How I know it didn't work with my directory? It didn't show my webhook in template list and it didn't remove templates I've removed (during the test) from the shown list. 
- [x ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x ] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [x ] Testing: The changes are tested.
- [x ] Documentation: Relevant documentation is added or updated.
> Adds template for AllThingsTalk webhook

- homey.yml
Updated logo URL to S3 bucket
Removed duplicate header (seems to be generated automatically when selecting JSON webhook format)
Other logo URLs (with different size images) suitable for use:
https://homey-logos.s3.eu-west-1.amazonaws.com/logos/128.png
https://homey-logos.s3.eu-west-1.amazonaws.com/logos/512.png
> Homey template update (logo & header changes)

- attmaker.yml
This change will fix the URL for the docs article.
- Updated URL for the docs article
> Add correct URL for docs

- anyviz.yml
- templates.yml
New webhook template for [AnyViz](https://www.anyviz.io)
- anyviz.yml: template for AnyViz
- templates.yml: Added new template to list
If you want to have a look, feel free to [register for free](https://portal.anyviz.io/?register=true). The TTN application data will be visible as soon as the first uplink message is forwarded.
> Added webhook template for AnyViz

- .github/workflows/validate.yml
- CODEOWNERS
Update the `CODEOWNERS` and update the validation CI
> CODEOWNERS and CI update

- mclimate.yml
- templates.yml
> MClimate webhook template

- blockbax.yml
- templates.yml
Webhook template related to https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/674
- ...
- ...
...
> Blockbax webhook template

- mclimate.yml
- templates.yml
> Change logo and remove api key 

- blockbax.yml
Follows up on the discussion at https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/674
Update on the docs can be found here: https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/753
- Added autoCreateSubjects as field and use as query param
- Updated the descriptions
- Change base-url to dedicated integration (with more user-friendly The Things Stack payload support)
...
> Added autoCreateSubjects query param

- tellsens-oyster.yml
- templates.yml
> Add tellsens Webhook template

- mclimate.yml
> doc: Fix join accept path

- telemetry2u.yml
- templates.yml
...
- Added Telemetry2U Webhook
...
> Add Webhook for Telemetry2U

- daizy.yml
- templates.yml
Adds a webhook template for integrations to https://daizy.io
- New template file `daizy.yml`
- Adds `daizy` to the list in `templates.yml`
Template has been tested with an instance of `lorawan-stack` in our test environment 
- [n/a] Documentation: Relevant documentation is added or updated.
> Add webhook template for daizy.io

- akenza.yml
Updates the akenza webhook to work with the new akenza platform.
- Updates the akenza webhook to work with the new akenza platform.
> Update akenza connector

- myiotopentech.yml
- templates.yml
my IoT open Tech integration. my IoT open Tech is an IoT platform developed upon ThingsBoard Community Edition.
...
- This is a new template
https://www.doc.my.iotopentech.io/integrations/the-things-network.html
...
> my IoT open Tech webhook template

- losant.yml
- templates.yml
This adds the Losant Webhook Template as an option to Integrations -> Webhooks.
- added losant.yml
- updated templates.yml to include losant
@nejraselimovic : Losant Webhook Template for your review.
> adding Losant Webhook template

- README.md
- schema/lorawan_webhook_templates.go
- schema/validate.go
Support normalized uplink path
References https://github.com/TheThingsNetwork/lorawan-stack/pull/5730
- Add `uplink-normalized` path
- Update docs links
> Support normalized uplink path

- templates.yml
- thingerio.yml
This pull request adds a webhook integration for [Thinger.io](https://thinger.io/)
- templates.yml
- thingerio.yml
It's been tested in a local The Things Stack deployment against Thinger.io platform.
More info at our developer documentation: https://docs.thinger.io/plugins/the-things-stack
Also, currently working in the documentation at The Things Stack Cloud Integrations section. Will link once uploaded.
> Add Thinger.io Webhook template

- blockbax.yml
This enables users to use Blockbax inbound connectors, which is our new recommended way of integrating with The Things Stack (see https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/933 for related docs / discussion).
- Removed Project ID
- Removed Auto create subjects option
- Introduced Endpoint field for specifying whole base-url
...
> Moved to simpler config

- blockbax.yml
Trailing slash caused unexpected behavior
Removed trailing slash because it causes unexpected behavior. 
- Removed trailing slash from uplink message
> Remove trailing slash

- .github/workflows/validate.yml
Closes #73 
- Update actions to versions that use `Node 16`
> Update to `node 16`

- pilot-things.yml
This file is a template file for integrating with the Pilot Things system.
- Initial version
- The data received from TTI has been implemented and tested
- [V] Scope: The referenced issue is addressed, there are no unrelated changes.
- [V] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [V] Testing: The changes are tested.
- [V] Documentation: Relevant documentation is added or updated.
> Create new pilot-things template

- widgelix.yml
> Update Widgelix logo path

- datacake.yml
previous URL is invalid
- ...
- ...
...
> updated_logo_url Datacake

- .github/workflows/upload-airtable.yml
Remove the POST from the curl command.
- Remove the POST from the curl command.
> remove POST from curl command

- bin/csv.js
Fix the id in tts-documentation-url (the url wasnt being added to the csv)
- Fix the id in tts-documentation-url
...
> Fix ID in tts-documentation-url
